# Wrangler configuration for Cloudflare Pages project

type = "javascript"

compatibility_date = "2025-01-02"
#compatibility_flags = ["nodejs_compat"]


name = "typesense-remix-worker"

[build]
command = "npm run build"

# Environment configurations (optional)
[env.production]
workers_dev = false
